### ISSUE TITLE
Generating a new project fails because of a missing `.yo-rc.json` file

### ISSUE THREAD

**Issue by jack-mcivor** [sicara/sicarator#56]
I am using Ubuntu, and ran:
```bash
sudo npm install -g yo
npm install -g sicara/sicarator
cd /home/hack/scratch
yo sicarator
// ...follow the steps
```
Which raised
```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/home/jack/scratch/.yo-rc.json'
    at Object.readdirSync (node:fs:1452:3)
    at exports.readdir (/usr/lib/node_modules/generator-sicarator/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/usr/lib/node_modules/generator-sicarator/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/usr/lib/node_modules/generator-sicarator/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at DirectoryReader.stream._read (/usr/lib/node_modules/generator-sicarator/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (node:internal/streams/readable:496:12)
    at readdirSync (/usr/lib/node_modules/generator-sicarator/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/usr/lib/node_modules/generator-sicarator/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/usr/lib/node_modules/generator-sicarator/node_modules/fast-glob/out/providers/reader-sync.js:64:24)
    at ReaderSync.api (/usr/lib/node_modules/generator-sicarator/node_modules/fast-glob/out/providers/reader-sync.js:56:25)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/jack/scratch/.yo-rc.json'
}

Node.js v18.16.0
```

It seems like some yeomen configuration file is missing? I'm not familiar with yeomen (or any js tools really), and am struggling to debug. Am I missing a step or have I botched the install?

**Comment by ywolff** [comment]
Hi, thanks for raising this issue!

I haven't got this problem with my current NodeJS version (16.20.0), but when I switched to the same NodeJS version as you, I have been able to reproduce your error. It seems than Yeoman handling of the `yo-rc.json` is different between versions...

I've coded [a fix](https://github.com/sicara/sicarator/pull/57), could you confirm that it works on your side before I merge it?
You can test the fix version by running:
`npm install -g "sicara/sicarator#fix-yo-rc-not-found"`
And retrying `yo sicarator`

Thank you in advance!

**Comment by jack-mcivor** [comment]
Thanks, that version works for me

**Comment by ywolff** [comment]
@jack-mcivor Perfect, thanks! I juste merged it.
